### ISSUE TITLE
Non Code Stuff

### ISSUE THREAD

**Issue by imbuedhope** [sdlynx/land-yacht#1]
We should really push non code stuff to the wiki in this project instead and use links to sample code instead.

I feel like it's going to get out of hand pretty fast.

Thoughts?

**Comment by sd5969** [comment]
Yes, you're right. I'll move some things around. I created a "resources" folder for non-code items since you can only link images in the wiki, not embed them. I don't think there's any
need to use links for sample code though if we plan on modifying it for
testing/use.
